- package.json
- schema.graphql
- src/aggregates/follows.ts
- src/aggregates/index.ts
- src/aggregates/shared.ts
- src/aggregates/views.ts
- src/entities/ChannelFollowsInfo.ts
- src/models/ChannelEvent.ts
- src/models/VideoEvent.ts
- src/models/shared.ts
- src/resolvers/followsInfo.ts
- src/resolvers/index.ts
- src/resolvers/viewsInfo.ts
- src/server.ts
Adds channel follow functionality. Also abstracted some common code for easier support of any future event types
Resolves #3
> add channel follow functionality

- .eslintrc.js
- .github/workflows/tests.yml
- .gitignore
- jest-mongodb-config.js
- jest.config.js
- package.json
- src/aggregates/follows.ts
- src/aggregates/index.ts
- src/aggregates/shared.ts
- src/aggregates/views.ts
- src/config.ts
- src/main.ts
- src/models/shared.ts
- src/resolvers/followsInfo.ts
- src/resolvers/viewsInfo.ts
- src/server.ts
- src/types.d.ts
- tests/follows.test.ts
- tests/queries/follows.ts
- tests/queries/views.ts
- tests/server.test.ts
- tests/setup.ts
- tests/views.test.ts
- tsconfig.build.json
- tsconfig.json
- yarn.lock
Adds integration tests using Jest. To do that I've also had to do some refactoring of the code so that it can be testable at all
Resolves #9
> add integration tests

- .gitignore
- schema.graphql
- src/aggregates/views.ts
- src/resolvers/viewsInfo.ts
- tests/queries/views.ts
- tests/views.test.ts
> Most viewed queries performance optimization

- schema.graphql
- src/entities/CategoryFeaturedVideos.ts
- src/resolvers/featuredContent.ts
- src/resolvers/queryNodeStitchingResolvers/featuredContentResolvers.ts
- src/server.ts
- tests/featuredContent.test.ts
- tests/queries/featuredContent.ts
Fix [#1849](https://github.com/Joystream/atlas/issues/1849)
> Improve allCategoriesFeaturedVideos query performance

- .eslintrc.js
- schema.graphql
- src/entities/ReportVideoInfo.ts
- src/models/ReportedContent.ts
- src/resolvers/index.ts
- src/resolvers/reportsInfo.ts
- src/server.ts
Fix https://github.com/Joystream/atlas/issues/3002
> Content reporting

- package.json
- src/resolvers/admin.ts
- yarn.lock
Update after https://github.com/Joystream/joystream/pull/4681
> Orion v1: Update `generateAppActionCommitment` impl.

- CHANGELOG.md
- package.json
> Update CHANGELOG and bump version to 2.2

- CHANGELOG.md
> :memo: Doc: update changelog for version 3.0.0

- src/mappings/content/nft.ts
> [Notitifations] Fix uninitialized type bug

- CHANGELOG.md
- package-lock.json
- package.json
- src/utils/overlay.ts
> fix: processor's overlay bug

- src/mappings/content/commentsAndReactions.ts
Fixes the orion processor not setting correctly the values for video liked/disliked data
> fix: :bug: Video Liked data unitialized

- src/mappings/content/commentsAndReactions.ts
- src/tests/integration/notifications.test.ts
add tests for video liked mapping to check correct notification deposit
> Orion notifications video liked

- src/mappings/content/commentsAndReactions.ts
Missing data for events:
- react to comment
- react to video
> fix: :bug: uninitialized notification data fields

- src/mail-scheduler/index.ts
- src/utils/globalEm.ts
- src/utils/notification/helpers.ts
adds process.env.config for typeorm entity manager setup
> fix: :art: process env not being read for db connection

- src/utils/offchainState.ts
adds global counter migration for account entity for version 3.0.2
> fix: :ambulance: account counter

- CHANGELOG.md
- package.json
- src/utils/auth.ts
adds cors origins for local atlas testing:
adds release notes
> Orion 303 final touches

- .github/workflows/tests.yml
- package.json
- scripts/generate-emails.js
- src/auth-server/emails/templates/mjml/notification.html.mst.mjml
- src/utils/notification/notificationsData.ts
- src/utils/notification/testing/formatJOY.test.ts
- https://github.com/Joystream/atlas/issues/5181
> 🩹 Fix JOY values in emails and footer

- CHANGELOG.md
- docs/operator-guide/index.md
- docs/operator-guide/tutorials/deploying-orion.md
- docs/operator-guide/tutorials/email-notifications.md
- docs/operator-guide/tutorials/local-testing.md
> docs: :memo: changelog

- src/server-extension/resolvers/AdminResolver/index.ts
> fix: :ambulance: remove extra return type from resolver

- src/utils/auth.ts
https://github.com/Joystream/atlas/issues/5704
> Extend session based on activity after initial expiry is over

- db/migrations/1708500753099-Data.js
- db/migrations/1708500753231-Views.js
- package-lock.json
- package.json
- schema/videos.graphql
- src/mappings/content/metadata.ts
Addresses https://github.com/Joystream/joystream/issues/5077
> Add is short field to video entity

- CHANGELOG.md
- package-lock.json
- package.json
- src/mappings/content/utils.ts
> Add notifications for previous top bidders in open auction

- src/server-extension/resolvers/AdminResolver/index.ts
should fix https://github.com/Joystream/atlas/issues/5971
> fixed notifications for featured NFTs
