package.json, schema.graphql, src/aggregate.ts, src/entities/VideoViewsInfo.ts, src/models/VideoEvent.ts, src/resolvers/videoViewsInfos.ts, src/server.ts, yarn.lock
This PR resolves #1 by switching Orion data model to be event-based. To ensure decent performance two approaches were used:
Our implementation is pretty loosely based on event sourcing. It doesn't follow it strictly as our use-case is pretty narrow and simple at this point. We save sequenced events to MongoDB, which can be used to build the aggregate (current state). For performance, we keep the full aggregate in memory so that most basic queries will not require any DB lookup at all. The aggregate is built upon Orion launch by parsing all the existing events. This approach should be pretty extensible in the future. Building on top of this to e.g. save channel follow/unfollow events should be fairly simple.
Using the most straight-forward approach of one Mongo document per event could …
=> switch to event-sourcing based data model

package.json, schema.graphql, src/config.ts, src/main.ts, src/models/Admin.ts, src/resolvers/admin.ts, yarn.lock
=> add support for AppAction signatures

package.json, src/resolvers/admin.ts, src/resolvers/helpers.ts, tsconfig.json, yarn.lock
- Update app action commitment computation to use the new `@joystream/js` implementation
- Prevent Orion from signing arbitrary `AppActionMetadata` (see: https://github.com/Joystream/orion/issues/80)
=> Update app action commitment, disallow signing arbitrary appActionMetadata

package-lock.json, src/server-extension/resolvers/NftResolver/index.ts
Fixes https://github.com/Joystream/atlas/issues/4141 by making a distinction between `OwnedNft` GraphQL type and `OwnedNft` entity in imports.
=> Fix `requestNftFeatured` mutation

src/server-extension/resolvers/VideosResolver/index.ts
Fix https://github.com/Joystream/atlas/issues/4158
We were getting the error ` "common column name \"id\" appears more than once in left table",` once we were adding channel fields to the query.
I fixed the issue and refactored this a bit. Replaced `unnest()` with ` array_position()`which seems to me more straightforward, readable, and understandable.
=> Fix SQL error, when running mostViewedVideosConnection query

package-lock.json, src/utils/offchainState.ts
When trying to execute migration script on production there was an error when trying to import video views, as the number of entities was very large (> 10k) and there was only a single query trying to insert them all into the database.
=> OffchainState fix: Batch inserts during import to avoid query errors

scripts/generate-schema-file.sh, src/utils/offchainState.ts
- Fix state import issue when trying to execute partial imports of tables that had `0` records during export
- Make `generate-schema-file.sh` executable w/o bash, so that it doesn't cause errors during docker build
=> Minor fixes ported from `user-accounts` branch

db/migrations/2100000000000-Indexes.js, db/postgres.conf
Fixes issues with long `ownedNftConnection` and `videoConnection` queries (improvements of over 10x) by adding some useful PostgreSQL indexes.
Addresses https://github.com/Joystream/atlas/issues/4227
=> Add `auction_type` and `member_metadata_avatar` indexes

src/utils/events.ts
addresses #113
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1204404358291458/1205517370057901) by [Unito](https://www.unito.io)
=> [Nara] remove mappings for 'VideoDeletedByModerator' & 'ChannelDeletedByModerator' events

src/mappings/content/commentsAndReactions.ts, src/tests/integration/notifications.test.ts, src/tests/integration/testUtils.ts
fixes: the issue related to
```
{"level":5,"time":1697443321233,"ns":"sqd:processor","err":{"generatedMessage":false,"code":"ERR_ASSERTION","actual":false,"expected":true,"operator":"==","stack":"AssertionError [ERR_ASSERTION]: uninitialized access\n    at CommentPostedToVideo.get comentId [as comentId] (/orion/lib/model/generated/_commentPostedToVideo.js:77:30)\n    at CommentPostedToVideo.toJSON (/orion/lib/model/generated/_commentPostedToVideo.js:89:28)\n    at Object.to (/orion/lib/model/generated/notification.model.js:38:68)\n    at Function.transformTo (/orion/node_modules/typeorm/util/ApplyValueTransformers.js:20:28)\n    at PostgresDriver.preparePersistentValue (/orion/node_modules/typeorm/driver/postgres/PostgresDriver.js:405:69)\n    at …
```
=> fix: comment id not added to notification data

schema/notifications.graphql, src/mappings/content/commentsAndReactions.ts, src/mappings/content/metadata.ts, src/mappings/content/nft.ts, src/mappings/content/utils.ts, src/server-extension/resolvers/ChannelsResolver/index.ts, src/utils/notification/notificationAvatars.ts, src/utils/notification/notificationLinks.ts, src/utils/notification/notificationsData.ts
=> 👥 Add member ids to `NotificationType`

CHANGELOG.md, db/migrations/1698832298051-Data.js, docs/operator-guide/tutorials/backups.md, package-lock.json, schema/membership.graphql, src/auth-server/tests/common.ts, src/mail-scheduler/tests/testUtils.ts, src/mappings/membership/index.ts, src/processor.ts, src/tests/integration/notifications.test.ts, src/tests/integration/run.sh, src/tests/integration/testUtils.ts, src/tests/migrations/export.json, src/tests/migrations/migration.test.ts, src/utils/events.ts, src/utils/globalEm.ts, src/utils/offchainState.ts
Updates notification branch after fix for the member handle bug (see #214 )
Notification links and data have been updated to reflect that (see #219 )
=> update notification branch with master

scripts/generate-emails.js, src/auth-server/emails/templates/mjml/notification.html.mst.mjml, src/mail-scheduler/utils.ts, src/utils/notification/notificationAvatars.ts
=> 🔧 One more notification email fix

package.json, src/server-extension/resolvers/AssetsResolver/index.ts, src/server-extension/resolvers/AssetsResolver/types.ts, src/server-extension/resolvers/AssetsResolver/utils.ts, src/server-extension/resolvers/ChannelsResolver/index.ts, src/server-extension/resolvers/ChannelsResolver/types.ts, src/utils/notification/notificationAvatars.ts
- https://github.com/Joystream/atlas/issues/5505
I still wasn't able to test via the external archive. The script doesn't send any emails. I'm assuming I should sync a local archive with `wss://atlas-dev.joystream.org/ws-rpc` but this takes forever for me.
=> 🤞 Fix the channel avatar url

db/migrations/1701263174334-Data.js, docs/developer-guide/tutorials/updating-schema.md
=> Orion notifications final

src/utils/offchainState.ts
The email delivery attempt entity was not exported in the offchain state
=> email delivery attempt export

src/server-extension/resolvers/CreatorToken/index.ts, src/server-extension/resolvers/CreatorToken/types.ts
Issue: if we first divide the staking amount by the total supply BigNumber will floor the result to 0 since it doesn't support decimal places
=> 🤑 Fix revenue share dividend estimation

db/migrations/1703692601653-Data.js, schema/token.graphql, src/mappings/token/index.ts
https://github.com/Joystream/atlas/issues/3848#issuecomment-1845266094
=> 🛕 Historical revenue share participants

src/mappings/token/index.ts, src/mappings/token/utils.ts
Pass `overlay` instance instead of the `entityManager` instance to CRT notification handlers.
=> fix: CRT notifications bug

src/mappings/token/index.ts
```
{"level":5,"time":1711375967343,"ns":"sqd:processor","err":{"stack":"TypeError: em.getRepository(...).findOne is not a function\n    at getNextIdForEntity (/orion/lib/utils/nextEntityId.js:14:60)\n    at addOffChainNotification (/orion/lib/utils/notification/helpers.js:135:76)\n    at addNotification (/orion/lib/utils/notification/helpers.js:209:15)\n    at /orion/lib/mappings/token/utils.js:244:110\n    at /orion/node_modules/p-limit/index.js:23:31\n    at run (/orion/node_modules/p-limit/index.js:23:43)\n    at /orion/node_modules/p-limit/index.js:45:20\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}}
```
In the mappings `ProjectToken.RevenueSplitIssued` mappings we were not passing the event entity to the `notifyTokenHolders` function, because …
=> fix: pass event entity arg to `notifyTokenHolders` function in `ProjectToken.RevenueSplitIssued`

CHANGELOG.md, package-lock.json, package.json, src/mappings/token/index.ts, src/server-extension/resolvers/CreatorToken/index.ts, src/server-extension/resolvers/CreatorToken/types.ts, src/utils/offchainState.ts
This fix makes it possible to unstake participant tokens after the current revenue share is finalized and the new revenue share is started
=> Fix: `ProjectToken.RevenueSplitLeft` mapping

src/mappings/token/utils.ts, src/tests/integration/notifications.test.ts, src/utils/nextEntityId.ts, src/utils/notification/helpers.ts, src/utils/notification/index.ts, src/utils/overlay.ts
While creating the runtime notifications [addRuntimeNotification](https://github.com/zeeshanakram3/orion/blob/master/src/utils/notification/helpers.ts#L181) function reads the nextEntityId for the new notification from the [db](https://github.com/zeeshanakram3/orion/blob/master/src/utils/notification/helpers.ts#L191). And, then use this _id_ to create a new entity in the overlay.
Now the problem is that if many concurrent notifications are being created e.g. `Promise.all([...])`. Then each concurrent call of `addRuntimeNotification` will read the same next entity ID from the db, and only one notification can be created.
Instead of using db to get the next entity ID, read the ID form the overlay and then update it too, so the each concurrent `addRuntimeNotification` instance has access to …
=> fix: avoiding IDs override/conflict while creating concurrent runtime notifications

CHANGELOG.md, package-lock.json, package.json, src/mappings/token/index.ts, src/mappings/token/utils.ts
=> fix: remove duplicate CRT notifications creation

CHANGELOG.md, package.json, src/mappings/content/commentsAndReactions.ts, src/mappings/content/nft.ts, src/mappings/content/utils.ts, src/mappings/content/video.ts, src/mappings/token/index.ts, src/mappings/utils.ts, src/processor.ts, src/server-extension/resolvers/AdminResolver/index.ts, src/server-extension/resolvers/AdminResolver/utils.ts, src/server-extension/resolvers/ChannelsResolver/index.ts, src/server-extension/resolvers/VideosResolver/index.ts, src/server-extension/utils.ts, src/utils/VideoRelevanceManager.ts, src/utils/notification/helpers.ts
- Processor (non-breaking changes)
- GraphQL server (non-breaking changes)
- Fixed video relevance calculation algorithm by:
- Ignoring `publishedBeforeJoystream` date if it's in the future,
- Fixing a bug with Joystream/YT creation weight formula,
- Introduced an age limit of 365 days to prevent negative relevance score 
- Fixed ineffective `videoRelevanceManager` calls in GraphQL server due to `videoRelevanceManager` not being turned on.
- Fixed a bug causing both GraphQL server and Processor services to run video relevance and language update loops (which only processor should be running)
- Fixed imports in GraphQl server and Processor by moving shared utilities to root `utils` directory to prevent mix-ups.
=> 4.1.1.: Video relevance fixes

archive/docker-compose.yml, archive/postgres.conf, db/postgres.conf, docker-compose.yml
- Only log [`mod` statements](https://www.postgresql.org/docs/current/runtime-config-logging.html#GUC-LOG-STATEMENT) (`INSERT`, `DELETE`, `UPDATE` etc.) and [statements that take longer than 1 second](https://www.postgresql.org/docs/current/runtime-config-logging.html#GUC-LOG-MIN-DURATION-STATEMENT).
- Set [`local`](https://docs.docker.com/engine/logging/drivers/local/) logging driver with log rotation in db docker services (`max 200 MB * 10 files = 2 GB`)
- Turn on `log_lock_waits`
=> Adjust db logs configuration

src/mappings/content/nft.ts, src/mappings/content/utils.ts
Aims to fix the issue outlined here: https://github.com/Joystream/joystream/issues/5180
The problem was that the NFT ownership for the auction was updated before it was checked for in the `maybeIncreaseChannelCumulativeRevenueAfterNft`. This would make it always fail. Added the option to pass `previousNftOwner` to the function to circumvent this issue where necessary.
cc @Lezek123
=> Fix NFT sale proceeds not registering in CRT revenue account

CHANGELOG.md, package-lock.json, package.json
- Processor:
- **(M) `Content.EnglishAuctionSettled`** (event handler)
- **(M) `Content.BidMadeCompletingAuction`** (event handler)
- **(M) `Content.OpenAuctionBidAccepted`** (event handler)
- State importing
- Export state script (`npm run offchain-state:export`)
- Default `docker-compose.yml` and `postgres.conf` configuration
- Fixed `Channel.cumulativeRevenue` calculation after NFT is sold on Open/English auction (https://github.com/Joystream/joystream/issues/5180)
- Added missing data to exported state (https://github.com/Joystream/orion/pull/358):
- `CreatorToken.isFeatured` field
- `Video.includeInHomeFeed` field
- `UserInteractionCount` entity
- Fixed import logic (now runs BEFORE processing any block > `exportBlockNumber`. This prevents state inconsistency in case …
=> 4.3.0 release

CHANGELOG.md, package-lock.json, package.json, src/scripts/generateMockData.ts, src/scripts/seedDb.ts
- Scripts:
- **(M)** `scripts/generateMockData.ts`
- **(M)** `scripts/seedDb.ts`
- Fixed a bug when running `npm run generate:mock-data` from within docker container (missing `schema.graphql`).
- Fixed invalid error message when input/output path not provided in `generate:mock-data` / `db:seed` scripts.
=> 4.4.1: Fix data mocking scripts (docker)
